/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DBusServiceAdaptor -a dbusserviceadaptor.h:dbusserviceadaptor.cpp com.marxoft.QDL.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSSERVICEADAPTOR_H_1385680248
#define DBUSSERVICEADAPTOR_H_1385680248

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.marxoft.QDL
 */
class DBusServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.marxoft.QDL")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.marxoft.QDL\">\n"
"    <method name=\"addUrls\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"urls\"/>\n"
"    </method>\n"
"    <method name=\"importUrls\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"urls\"/>\n"
"    </method>\n"
"    <method name=\"retrieveUrls\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"urls\"/>\n"
"    </method>\n"
"    <method name=\"getTransfers\">\n"
"      <annotation value=\"QVariantList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"downloads\"/>\n"
"    </method>\n"
"    <method name=\"getTransfer\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"downloads\"/>\n"
"    </method>\n"
"    <method name=\"getTransferProperty\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"property\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"setTransferProperty\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"property\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"value\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"success\"/>\n"
"    </method>\n"
"    <method name=\"start\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"success\"/>\n"
"    </method>\n"
"    <method name=\"pause\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"success\"/>\n"
"    </method>\n"
"    <method name=\"start\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"success\"/>\n"
"    </method>\n"
"    <method name=\"pause\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"success\"/>\n"
"    </method>\n"
"    <method name=\"remove\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"success\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DBusServiceAdaptor(QObject *parent);
    virtual ~DBusServiceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void addUrls(const QStringList &urls);
    QVariantMap getTransfer(const QString &id);
    QDBusVariant getTransferProperty(const QString &id, const QString &property);
    QVariantList getTransfers();
    void importUrls(const QStringList &urls);
    bool pause(const QString &id);
    bool pause();
    bool remove(const QString &id);
    void retrieveUrls(const QStringList &urls);
    bool setTransferProperty(const QString &id, const QString &property, const QDBusVariant &value);
    bool start(const QString &id);
    bool start();
Q_SIGNALS: // SIGNALS
};

#endif
