/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c DBusServiceInterface -p dbusserviceinterface.h:dbusserviceinterface.cpp com.marxoft.QDL.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusserviceinterface.h"

/*
 * Implementation of interface class DBusServiceInterface
 */

DBusServiceInterface::DBusServiceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DBusServiceInterface::~DBusServiceInterface()
{
}

